"""
FastAPI application factory with lifespan dependency management.

Key design decisions:
1. Factory pattern — create_app() returns a configured FastAPI instance.
   This makes the app testable (tests call create_app() with overridden deps).

2. Lifespan context manager — replaces deprecated @app.on_event("startup").
   Dependencies are initialized once at startup and cleaned up at shutdown.
   Stored in app.state.deps and accessed in route handlers via request.app.state.deps.

3. Logging configured at startup with a structured format.

Usage:
    # Start the server
    uvicorn src.api.app:app --reload --port 8000

    # Interactive API docs (auto-generated by FastAPI)
    http://localhost:8000/docs

    # OpenAPI schema
    http://localhost:8000/openapi.json
"""

import logging
from contextlib import asynccontextmanager

from fastapi import FastAPI

from src.api.middleware import register_middleware
from src.api.routes import chat_router
from src.config import load_settings
from src.dependencies import create_app_dependencies

# ── Logging configuration ──────────────────────────────────────────────────────

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)-8s | %(name)s | %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)

logger = logging.getLogger(__name__)


# ── Lifespan ───────────────────────────────────────────────────────────────────

@asynccontextmanager
async def lifespan(app: FastAPI):
    """
    FastAPI lifespan context manager.

    Code before 'yield' runs at startup.
    Code after 'yield' runs at shutdown.

    Why lifespan over @app.on_event("startup")?
    - @app.on_event is deprecated as of FastAPI 0.95+
    - lifespan is the modern, official approach
    - Cleaner resource management: startup + shutdown in one place
    - Better error handling: exceptions during startup fail-fast before accepting requests

    Startup:
    - Loads settings from .env
    - Initializes all providers (embedding, ChromaDB, Groq)
    - Compiles the LangGraph state machine
    - Stores everything in app.state.deps

    Shutdown:
    - No explicit cleanup needed (ChromaDB persists to disk automatically)
    - Future: add connection pool teardown, Redis disconnection, etc.
    """
    logger.info("Starting ShopEase Customer Support API ...")

    try:
        settings = load_settings()
        deps = create_app_dependencies(settings)
        app.state.deps = deps
        logger.info("Startup complete. API is ready to serve requests.")
    except Exception as e:
        logger.critical(f"Startup failed: {e}")
        raise  # Re-raise: FastAPI will not start if lifespan raises

    yield  # Application runs here — handling requests

    # Shutdown (currently no-op; add cleanup here if needed in future)
    logger.info("Shutting down ShopEase Customer Support API ...")


# ── App factory ────────────────────────────────────────────────────────────────

def create_app() -> FastAPI:
    """
    Factory function that creates and configures the FastAPI application.

    Returns a fully configured FastAPI instance with:
    - Lifespan dependency management
    - CORS, request logging, and global error handling middleware
    - Chat and health routes registered

    Testability:
    Tests call create_app() and override app.state.deps with mock dependencies
    before calling the TestClient, enabling offline unit testing.
    """
    app = FastAPI(
        title="ShopEase Customer Support API",
        description=(
            "Adaptive Self-Healing RAG system for e-commerce customer support. "
            "Routes queries through cost-optimized LLM paths, self-corrects "
            "retrieval quality, and fact-checks every response."
        ),
        version="0.1.0",
        lifespan=lifespan,
        docs_url="/docs",
        redoc_url="/redoc",
    )

    # Register middleware (CORS, logging, error handler)
    register_middleware(app)

    # Register route handlers
    app.include_router(chat_router)

    return app


# ── Application instance ───────────────────────────────────────────────────────
# Uvicorn imports this object: `uvicorn src.api.app:app --reload --port 8000`

app = create_app()
